const LOW_STOCK_THRESHOLD = 10;

const ORDER_STATUS = {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED"
};

const EVENT_NAMES = {
    LOW_STOCK: "LOW_STOCK",
    ORDER_CREATED: "ORDER_CREATED",
    STOCK_UPDATED: "STOCK_UPDATED",
    ORDER_CANCELLED: "ORDER_CANCELLED"
};

const CACHE_KEYS = {
    MEDICINES: "medicines:all",
    MEDICINE: "medicine:"
};

const CACHE_TTL = {
    MEDICINES: 300,
    MEDICINE: 300
};

const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500
};

module.exports = {
    LOW_STOCK_THRESHOLD,
    ORDER_STATUS,
    EVENT_NAMES,
    CACHE_KEYS,
    CACHE_TTL,
    HTTP_STATUS
};